pipeline {
    agent { docker { image 'gradle:6.6.0-jdk14' } }
    stages {
        stage('build') {
            steps {
                sh 'cd example-project; gradle build'
            }
        }
    }
}
